services:
  frontend:
    image: melvincv/springbootcrudapp:$TAG
    restart: unless-stopped
    ports:
      - 8100:8080
    networks:
      - int
      - ext
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - int
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 10000:8080
    networks:
      - int
      - ext
    depends_on:
      - db

networks:
  ext:
  int:

volumes:
  db-data:
