version: '3.1'

services:

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: testdb


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: